//types
const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'

module.exports = {FETCH_DATA_FAILURE, FETCH_DATA_SUCCESS, FETCH_USERS_REQUEST}